############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Team"
url = "/team"
weight = 3

[[main]]
name = "Services"
url = "/services"
weight = 4

[[main]]
name = "Themes"
url = "/themes"
weight = 5

[[main]]
name = "SalmonVision"
url = "/themes/salmonvision"
parent = "Themes"

[[main]]
name = "Aerial Salmon"
url = "/themes/aerialsalmon"
parent = "Themes"

[[main]]
name = "Large Scale Coastal Mapping"
url = "/themes/dronecoast"
parent = "Themes"

[[main]]
name = "Trout Identification"
url = "/themes/trout-reid"
parent = "Themes"

[[main]]
name = "Contact"
url = "https://salmonvision.org/contact/"
weight = 6

# [[main]]
# weight = 4
# name = "Pages"

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "/blog"

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "/contact"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "/authors"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"



[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Team"
url = "/team"
weight = 3

[[footer]]
name = "Services"
url = "/services"
weight = 4

[[footer_sub]]
name = "SalmonVision"
url = "/themes/salmonvision"
weight = 1

[[footer_sub]]
name = "Aerial Salmon"
url = "/themes/aerialsalmon"
weight = 2

[[footer_sub]]
name = "Large Scale Coastal Mapping"
url = "/themes/dronecoast"
weight = 3

[[footer_sub]]
name = "Trout Identification"
url = "/themes/trout-reid"
weight = 4


