baseURL = "https://lumax.ai/"
languageCode = "en-us"
title = "Lumax"

[params]
  description = "Field Data. Ecological Analytics. Conservation Impact."

  [params.contact]
    title = "Tell us what you are trying to understand."
    cta = "start a project"
    email = "hello@lumax.ai"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "#projects"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "#about"
    weight = 2
  [[menu.main]]
    identifier = "services"
    name = "services"
    url = "#services"
    weight = 3
  [[menu.main]]
    identifier = "resources"
    name = "resources"
    url = "#resources"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true
